project_4/config/routes.rb
Rails.application.routes.draw do
  get '/products/:id/delete', to: "products#destroy"
  devise_for :users 
  resources :products
  resources :customer
  resources :dairy
  resources :meats
  resources :fruits
  resources :home





 

  get 'welcome/index'
  root to: "welcome#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

project_4/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

project_4/app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image
end

project_4/app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

project_4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected
         def configure_permitted_parameters
            
          devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:firstname, :lastname, :username, :dob, :email, :phone, :password) }
            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
         end
end

project_4/app/controllers/customer_controller.rb
class CustomerController < ApplicationController
    def index
    end
 
 
end

project_4/app/controllers/dairy_controller.rb
class DairyController < ApplicationController

def index
    @product = Product.all
end
end

project_4/app/controllers/fruits_controller.rb
class FruitsController < ApplicationController

    def index
        @product = Product.all
    end
    end
    

project_4/app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        @product = Product.all
    end
    end
    

project_4/app/controllers/meats_controller.rb
class MeatsController < ApplicationController

    def index
        @product = Product.all
    end
    end
    

project_4/app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @product = Product.all

    
    end
    def new
        @product = Product.new
    
    end
    def show
    
            @product =Product.find(params[:id])


    end


    def create 
         @product =Product.new(product_params)
    
       if(@product.save)
        redirect_to @product
       else
        render 'new'
       end
    end


    def edit
        @product =Product.find(params[:id])
    end


    def update
        @product =Product.find(params[:id])
        if(@product.update(product_params))
            redirect_to @product
           else
            render 'edit'
           end
    end
    def destroy
        @product =Product.find(params[:id])
        @product.destroy
        redirect_to products_path
    
    end

 
    private 
    def product_params
        params.require(:product).permit(:productname,:DanubPrice,:PandaPrice,:ManualPrice,:image, :product_type)
    end
    
    
    end
    

project_4/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, :except =>[:index]

 
  def index
  end
end

project_4/app/helpers/application_helper.rb
module ApplicationHelper
end

project_4/app/helpers/customer_helper.rb
module CustomerHelper
end

project_4/app/helpers/dairy_helper.rb
module DairyHelper
end

project_4/app/helpers/fruits_helper.rb
module FruitsHelper
end

project_4/app/helpers/home_helper.rb
module HomeHelper
end

project_4/app/helpers/meats_helper.rb
module MeatsHelper
end

project_4/app/helpers/products_helper.rb
module ProductsHelper
end

project_4/app/helpers/welcome_helper.rb
module WelcomeHelper
end

project_4/app/views/customer/index.html.erb
<center>
<div class="container">
<div class="jumbotron">

<div class="row">
<div class="col">
 <%= link_to image_tag("https://www.aljoumhouria.com/files/news/436/images/preview/dairy-products.jpg ", :style=> 'width:300px')  ,"http://localhost:3000/dairy"%>

<h3> Dairy </h3>
<br>
</div>
<div class="col">
 <%= link_to image_tag("https://images.alwatanvoice.com/news/large/9998902606.jpg", :style=> 'width:300px') ,"http://localhost:3000/meats"%>
<h3> Meats </h3>
<br>

</div>


</div>

<br>
<br>

<div class="row">
<div class="col">
 <%= link_to image_tag("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ_p5x5auV2J_1-TYZFcKuGBdVRAQl4r9dXLnwgDwwu07kHIs3s", :style=> 'width:300px') ,"http://localhost:3000/fruits"%>

<h3> Fruits & Vegetabels</h3>


</div>
<div class="col">
<%= link_to image_tag("https://3.bp.blogspot.com/-o6DLXdigKYA/VeTkx6j3KrI/AAAAAAAABAc/fhF_JHAEu-I/s1600/chlorine-bleach-with-ammonia-acids-detergents-compressor.jpg", :style=> 'width:300px') ,"http://localhost:3000/home"%>

 <h3> Home </h3>
</div>


</div>
</div>
</div>
</center>

project_4/app/views/dairy/index.html.erb
<center><h3> dairy </h3></center>

<center>
<div class="container">
<div class="jumbotron">

<% @product.each do |product| %>
    <% if product.product_type=='dairy'%>


    <div class="well">
       <h3>Product Name <%= product.productname %></h3>
       <p> <%= image_tag product.image , :style=> 'width:300px' %></p>

        <p>Panda Price <%= product.PandaPrice %></p>
       <p>Danub Price <%= product.DanubPrice %></p>
       <p>Manual Price <%= product.ManualPrice %></p>

       
       <%= link_to "Details " , product_path(product), :class => 'btn btn-default' %>
   </div>
   <% end %>
   <% end %>
</div> 
</div>
</center>

project_4/app/views/dairy/show.html.erb
<h3> dairy </h3>


<% @product.each do |product| %>


    <div class="well">
       <h3>Product Name <%= product.productname %></h3>
       <p> <%= image_tag(product.image) %></p>
       <p>Panda Price <%= product.PandaPrice %></p>
       <p>Danub Price <%= product.DanubPrice %></p>
       <p>Manual Price <%= product.ManualPrice %></p>

       
       <%= link_to "Details " , product_path(product), :class => 'btn btn-default' %>
   </div>
  <% end %>

project_4/app/views/fruits/index.html.erb
 
   <center><h3> Fruits </h3>   </center>
<center>
<div class="container">
<div class="jumbotron">

<% @product.each do |product| %>
    <% if product.product_type=='fruitsVagetabels'%>


    <div class="well">
       <h3>Product Name <%= product.productname %></h3>
       <p> <%= image_tag product.image , :style=> 'width:300px' %></p>
        <p>Panda Price <%= product.PandaPrice %></p>
       <p>Danub Price <%= product.DanubPrice %></p>
       <p>Manual Price <%= product.ManualPrice %></p>

       
       <%= link_to "Details " , product_path(product), :class => 'btn btn-default' %>
   </div>
   <% end %>
   <% end %>
   </div> 
   </div>
   </center>

project_4/app/views/home/index.html.erb
<center><h3> Home </h3>   </center>

<center>
<div class="container">
<div class="jumbotron">

<% @product.each do |product| %>
    <% if product.product_type=='home'%>


    <div class="well">
       <h3>Product Name <%= product.productname %></h3>
        <p> <%= image_tag product.image , :style=> 'width:300px' %></p>

        <p>Panda Price <%= product.PandaPrice %></p>
       <p>Danub Price <%= product.DanubPrice %></p>
       <p>Manual Price <%= product.ManualPrice %></p>

       
       <%= link_to "Details " , product_path(product), :class => 'btn btn-default' %>
   </div>
   <% end %>
   <% end %>
   </div> 
   </div>
   </center>

project_4/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>project4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<nav class="navbar  navbar-light" style="background-color: #ffcc00;" "fixed-top">

<a class="navbar-brand mb-1 h1"style="font-size: 30px;" href="#">project</a>
<nav class="nav justify-content-end">
    <% if user_signed_in? %>
      Logged in as :  <strong>  <%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </nav>
</nav>
<% if notice %>
<p class="alert alert-success"><%= notice %></p>
<% end %>  
<% if alert %>
   <p class="alert alert-danger"><%= alert %></p>
<% end %>
<br>
<br>
<br>
<br>

    <%= yield %>
  </body>
</html>

project_4/app/views/meats/index.html.erb
<center><h3> Meats </h3>   </center>

<center>
<div class="container">
<div class="jumbotron">

<% @product.each do |product| %>
    <% if product.product_type=='meat'%>


    <div class="well">
       <h3>Product Name <%= product.productname %></h3>
       <p> <%= image_tag product.image , :style=> 'width:300px' %></p>

        <p>Panda Price <%= product.PandaPrice %></p>
       <p>Danub Price <%= product.DanubPrice %></p>
       <p>Manual Price <%= product.ManualPrice %></p>

       
       <%= link_to "Details " , product_path(product), :class => 'btn btn-default' %>
   </div>
   <% end %>
   <% end %>
   </div> 
   </div>
   </center>

project_4/app/views/products/edit.html.erb
<center>
<div class="container">
<div class="jumbotron">
<h1> edit products</h1>
 

<%= form_for :product , url: product_path(@product), method: :patch do |f| %>
 
    <p>
          <%= f.label :productname %><br>
          <%= f.text_field(:productname , {:class => 'form-control'}) %>

    </p>
    <p>
          <%= f.label :DanubPrice %><br>
          <%= f.number_field(:DanubPrice, {:class => 'form-control'}) %>

    </p>
    <p>
    <%= f.label :PandaPrice %><br>
    <%= f.number_field(:PandaPrice, {:class => 'form-control'}) %>

</p>
 
<p>
<%= f.label :ManualPrice %><br>
<%= f.number_field(:ManualPrice, {:class => 'form-control'}) %>

</p>

<p>
<%= f.label :image %><br>
<%= f.file_field(:avater, {:class => 'form-control'}) %>

</p>
    <p>
           <%= f.submit({:class => 'btn btn-primary'}) %>

    </p>
    <% end %>



</div>
</div>
 </center>

project_4/app/views/products/index.html.erb
<center>

<div class="container">

<h1> index products</h1>
 
<div class="form-row">
<div class="col-md-6 mb-3">
 <div class="jumbotron">
 <h1> Dairy </h1>
<% @product.each do |product| %>
    
    <% if product.product_type=="dairy" %>
 
    <div class="well">
       <h3>Product Name <%= product.productname %></h3>
       <p> <%= image_tag(product.image , :style=> 'width:300px') %></p>
       <p>Panda Price <%= product.PandaPrice %></p>
       <p>Danub Price <%= product.DanubPrice %></p>
       <p>Manual Price <%= product.ManualPrice %></p>

       
       <%= link_to "Details " , product_path(product), :class => 'btn btn-default' %>
   </div>
        <% end %>  
        
        <% end %>  
   </div>

   <div class="jumbotron">
        <h1> Meat </h1>
<% @product.each do |product| %>
    
    <% if product.product_type=="meat" %>
 
    <div class="well">
       <h3>Product Name <%= product.productname %></h3>
       <p> <%= image_tag(product.image , :style=> 'width:300px') %></p>
       <p>Panda Price <%= product.PandaPrice %></p>
       <p>Danub Price <%= product.DanubPrice %></p>
       <p>Manual Price <%= product.ManualPrice %></p>

       
       <%= link_to "Details " , product_path(product), :class => 'btn btn-default' %>
   </div>
        <% end %>  
        
        <% end %>  

        </div>

        <div class="jumbotron">
        <h1> Home </h1>
<% @product.each do |product| %>
    
    <% if product.product_type=='home'%>
 
    <div class="well">
       <h3>Product Name <%= product.productname %></h3>
       <p> <%= image_tag(product.image , :style=> 'width:300px') %></p>
       <p>Panda Price <%= product.PandaPrice %></p>
       <p>Danub Price <%= product.DanubPrice %></p>
       <p>Manual Price <%= product.ManualPrice %></p>

       
       <%= link_to "Details " , product_path(product), :class => 'btn btn-default' %>
   </div>
        <% end %>  
        
        <% end %>  

        </div>

        <div class="jumbotron">
        <h1> Fruits </h1>
<% @product.each do |product| %>
    
    <% if product.product_type=='fruitsVagetabels'%>
 
    <div class="well">
       <h3>Product Name <%= product.productname %></h3>
       <p> <%= image_tag(product.image , :style=> 'width:300px') %></p>
       <p>Panda Price <%= product.PandaPrice %></p>
       <p>Danub Price <%= product.DanubPrice %></p>
       <p>Manual Price <%= product.ManualPrice %></p>

       
       <%= link_to "Details " , product_path(product), :class => 'btn btn-default' %>
   </div>
        <% end %>  
        
        <% end %>  

        </div>

       



       </div>

   
       </div>


</div>
 </center>

project_4/app/views/products/new.html.erb
<center>
<div class="container">
<div class="jumbotron">
<h1> add products</h1>
 

<%= form_for :product , url: products_path do |f| %>
 
    <p>
          <%= f.label :productname %><br>
          <%= f.text_field(:productname , {:class => 'form-control'}) %>

    </p>
    <p>
          <%= f.label :product_type%><br>
          <%= f.select :product_type, ['dairy', 'meat','fruitsVagetabels','home'] %>
    </p>
    <p>
          <%= f.label :DanubPrice %><br>
          <%= f.number_field(:DanubPrice, {:class => 'form-control'}) %>

    </p>
    
  
<p>
<%= f.label :PandaPrice %><br>
<%= f.number_field(:PandaPrice, {:class => 'form-control'}) %>

</p>
<p>
<%= f.label :ManualPrice %><br>
<%= f.number_field(:ManualPrice, {:class => 'form-control'}) %>

</p>

<p>
<%= f.label :image %><br>
<%= f.file_field( :image , {:class => 'form-control'})%>

</p>
    <p>
           <%= f.submit({:class => 'btn btn-primary'}) %>

    </p>
    <% end %>



</div>
</div>
 </center>

project_4/app/views/products/show.html.erb
<center>
<div class="container">
<div class="jumbotron">
<%= image_tag(@product.image) %>
<h2>Product Name <%= @product.productname %> </h2>
<h2>Panda Price <%= @product.PandaPrice %> </h2>
<h2>Danub Price <%= @product.DanubPrice %> </h2>
<h2>Manual Price <%= @product.ManualPrice %> </h2>



<%= link_to "edit" , edit_product_path(@product), :class => 'btn btn-default' %>
<%= link_to "Delete" , 
"/products/#{@product.id}/delete", 
                    data: {confirm: 'Are you sure'},
                            :class => 'btn btn-danger' %>
                          
                             </div>
</div>
 </center>

project_4/app/views/welcome/index.html.erb
<center>
<div class="container">
<div class="jumbotron">
<button class="btn btn-outline-info" > <%= link_to"Add a product" ,new_product_path  %></button>
<button class="btn btn-outline-info"> <%= link_to"Show all products" ,products_path %>  </button>

</div>
</div>
 </center>